FORMAT: 1A
HOST: http://www.google.com


# grups
Notes API is a *short texts saving* service similar to its physical paper presence on your table.

# Group Skupina

## Groups Collection [/groups]
### Seznam skupin [GET]
+ Response 200 (application/json)

        [
            {
                "id": 1, 
                "name": "A-Team",
                "category": {
                    "name": "Heroes",  
                },
                "creator": {
                    "id": 1,
                    "name": "B. A. Baracus",
                },
                "members": [
                    {
                        "id": 2,
                        "name": "John Smith",
                        "image": "/users/images/1315648.jpg"
                        "admin": true
                    },
                    {
                        "id": 3,
                        "name": "Templeton Peck",
                        "image": "/users/images/1315648.jpg",
                        "admin": false
                    },
                    
                ],
                "notifications": []
            }
        ]



## Group [/groups/{id}]
Popis skupiny

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Note to perform action with. Has example value.

### Skupina [GET]
+ Response 200 (application/json)

    + Body

            { 
                "id": 1,
                "name": "A-Team",
                "members": [
                    {
                        "id": 2,
                        "name": "John Smith",
                        "image": "/users/images/1315648.jpg"
                    },
                    {
                        "id": 3,
                        "name": "Templeton Peck",
                        "image": "/users/images/1315648.jpg"
                    },
                    
                ],
                "topics": [
                    {
                        "name": "Doručení slivovice prezidentovi",
                        "responsiblePerson": {
                            "id": 3,
                            "name": "Templeton Peck",
                            "image": "/users/images/1315648.jpg"
                        }
                        "dueDate": {
                            "date": "2013-01-31 11:14:05",
                            "timezoneType": 3,
                            "timezone": "America\/Los_Angeles"
                        }
                        "status" : {
                            "id": 1,
                            "name": "Ready",
                            "colour": "fff",
                        }
                        "tags": [
                            {
                                "id" : 1,
                                "name": "asap",
                            },
                            {
                                "id" : 2,
                                "name": "alkohol",
                            },
                        ]
                    }
                ]
            }
      
## Stream [/groups/{id}/posts]
Příspěvky hlavního streamu skupiny (bez připnutých příspěvků), pro kompletní výpis je potřeba zavolat také `/groups/{id}/posts?pinned=1` 

Atributy postu:

- `type` - 1 pokud se jedná o klasický příspěvek a obsahuje parametr `message`, 2 pokud jde o událost(i) a obsahuje `events` (př. přidání uživatele do skupiny)


### Skupina [GET]
+ Response 200 (application/json)

    + Body

            { 
                "total": 500,
                "page": 0,
                "limit": 20,
                "posts": [
                    {
                        "type" : 1,
                        "user": {
                            "id": 3,
                            "name": "Templeton Peck",
                            "image": "/users/images/1315648.jpg"
                        },
                        "message": {
                            "createdDate": {
                                "date": "2013-01-31 11:14:05",
                                "timezoneType": 3,
                                "timezone": "America\/Los_Angeles"
                            },
                            "modifiedDate": {
                                "date": "2013-01-31 11:14:05",
                                "timezoneType": 3,
                                "timezone": "America\/Los_Angeles"
                            },
                            "content": "Přeji všem úspěšnou akci"
                        }
                    },
                    {
                        "type" : 2,
                        "user": {
                            "id": 3,
                            "name": "Templeton Peck",
                            "image": "/users/images/1315648.jpg"
                        },
                        "events": [
                            {
                                "id": 1,
                                "type": 1,
                                "createdDate": {
                                    "date": "2013-01-31 11:14:05",
                                    "timezoneType": 3,
                                    "timezone": "America\/Los_Angeles"
                                },
                            },
                            {
                                "id": 2,
                                "type": 2,
                                "createdDate": {
                                    "date": "2013-01-31 11:14:05",
                                    "timezoneType": 3,
                                    "timezone": "America\/Los_Angeles"
                                },
                            }
                        ]
                    }
                ]
            }
      
            
## Připnuté příspěvky [/groups/{id}/posts?pinned=1]
Připnuté příspěvky hlavního streamu skupiny seřazené podle data, neobsahuje `events`


### Připnuté příspěvky [GET]
+ Response 200 (application/json)

    + Body

            [
                {
                    "user": {
                        "id": 3,
                        "name": "Templeton Peck",
                        "image": "/users/images/1315648.jpg"
                    },
                    "message": {
                        "createdDate": {
                            "date": "2013-01-31 11:14:05",
                            "timezoneType": 3,
                            "timezone": "America\/Los_Angeles"
                        },
                        "modifiedDate": {
                            "date": "2013-01-31 11:14:05",
                            "timezoneType": 3,
                            "timezone": "America\/Los_Angeles"
                        },
                        "content": "UPOZORNĚNÍ: Akce se bude konat příští měsíc"
                    }
                }
            ]
            

# Group Téma

## Topics Collection [/topics/{id}]
### Téma skupiny [GET]
+ Response 200 (application/json)

        [
            {
                "id": 1, 
                "name": "A-Team",
                "category": {
                    "name": "Heroes",  
                },
                "creator": {
                    "id": 1,
                    "name": "B. A. Baracus",
                },
                "members": [
                    {
                        "id": 2,
                        "name": "John Smith",
                        "image": "/users/images/1315648.jpg"
                        "admin": true
                    },
                    {
                        "id": 3,
                        "name": "Templeton Peck",
                        "image": "/users/images/1315648.jpg",
                        "admin": false
                    },
                    
                ],
                "notifications": []
            }
        ]

## Stream [/topics/{id}/posts]
Příspěvky streamu tématu (bez připnutých příspěvků), pro kompletní výpis je potřeba zavolat také `/groups/{id}/posts?pinned=1` 

Atributy postu:

- `type` - 1 pokud se jedná o klasický příspěvek a obsahuje parametr `message`, 2 pokud jde o událost(i) a obsahuje `events` (př. přidání uživatele do skupiny)


### Skupina [GET]
+ Response 200 (application/json)

    + Body

            { 
                "total": 500,
                "page": 0,
                "limit": 20,
                "posts": [
                    {
                        "type" : 1,
                        "user": {
                            "id": 3,
                            "name": "Templeton Peck",
                            "image": "/users/images/1315648.jpg"
                        },
                        "message": {
                            "createdDate": {
                                "date": "2013-01-31 11:14:05",
                                "timezoneType": 3,
                                "timezone": "America\/Los_Angeles"
                            },
                            "modifiedDate": {
                                "date": "2013-01-31 11:14:05",
                                "timezoneType": 3,
                                "timezone": "America\/Los_Angeles"
                            },
                            "content": "Přeji všem úspěšnou akci"
                        }
                    },
                    {
                        "type" : 2,
                        "user": {
                            "id": 3,
                            "name": "Templeton Peck",
                            "image": "/users/images/1315648.jpg"
                        },
                        "events": [
                            {
                                "id": 1,
                                "type": 1,
                                "createdDate": {
                                    "date": "2013-01-31 11:14:05",
                                    "timezoneType": 3,
                                    "timezone": "America\/Los_Angeles"
                                },
                            },
                            {
                                "id": 2,
                                "type": 2,
                                "createdDate": {
                                    "date": "2013-01-31 11:14:05",
                                    "timezoneType": 3,
                                    "timezone": "America\/Los_Angeles"
                                },
                            }
                        ]
                    }
                ]
            }
      
            
## Připnuté příspěvky [/topics/{id}/posts?pinned=1]
Připnuté příspěvky hlavního streamu skupiny seřazené podle data, neobsahuje `events`


### Připnuté příspěvky [GET]
+ Response 200 (application/json)

    + Body

            [
                {
                    "user": {
                        "id": 3,
                        "name": "Templeton Peck",
                        "image": "/users/images/1315648.jpg"
                    },
                    "message": {
                        "createdDate": {
                            "date": "2013-01-31 11:14:05",
                            "timezoneType": 3,
                            "timezone": "America\/Los_Angeles"
                        },
                        "modifiedDate": {
                            "date": "2013-01-31 11:14:05",
                            "timezoneType": 3,
                            "timezone": "America\/Los_Angeles"
                        },
                        "content": "UPOZORNĚNÍ: Akce se bude konat příští měsíc"
                    }
                }
            ]






