FORMAT: 1A
HOST: http://www.google.com

# Grups
Všechna data jsou v GMT a uživatelé mají uložené vlastní časové pásmo, pomocí kterého následně frontend zajistí správné formátování výpisu

Prefix všech volání `/api/v<verze>/<locale>` př. `/api/v1/cs/`

# TODO
- návratové hodnoty po POST, PUT, DELETE
- návratové hodnoty chyb
- autorizace
- CSFR
- přidalat případné řazení a filtraci, kde bude potřeba
- Call na notifikace



# Group Skupina

## Groups Collection [/groups]
### Seznam skupin [GET]

Vrátí seznam pro výpis na homepage. Podle `type` se rozhoduje jestli `1`=skupinam, `2`=kategorie se skupinami

+ Response 200 (application/json)

        [
            {
                "id": 1, 
                "name": "A-Team",
                "type": 1,
                "members": [
                    {
                        "id": 2,
                        "name": "John Smith",
                        "image": "/users/images/1315648.jpg"
                        "admin": true
                    },
                    {
                        "id": 3,
                        "name": "Templeton Peck",
                        "image": "/users/images/1315648.jpg",
                        "admin": false
                    },
                    
                ],
                "notifications": []
            },{
                "id": 3, 
                "name": "Kategorie ABC",
                "type": 2,
                "groups":[
                    {
                        "id": 1, 
                        "name": "A-Team",
                        "type": 1,
                        "members": [
                            {
                                "id": 2,
                                "name": "John Smith",
                                "image": "/users/images/1315648.jpg"
                                "admin": true
                            },
                            {
                                "id": 3,
                                "name": "Templeton Peck",
                                "image": "/users/images/1315648.jpg",
                                "admin": false
                            },
                            
                        ],
                        "notifications": []
                    }
                ]
            }
        ]
        
### Vytvoření skupiny [POST]
+ Request (application/json)

        {
            "name": "Fantastic Four",
        }
+ Response 201 (application/json)
    
        {
            "id": 1,
            "name": "Fantastic Four",
            "hash": "07ced4ccbec3ab8e8d0ed617408f5818"
            "image"
        }


## Group [/groups/<id>]
Popis skupiny

### Informace skupiny [GET]
+ Response 200 (application/json)

    + Body

            { 
                "id": 1,
                "name": "A-Team",
                "members": [
                    {
                        "id": 2,
                        "name": "John Smith",
                        "image": "/users/images/1315648.jpg"
                    },
                    {
                        "id": 3,
                        "name": "Templeton Peck",
                        "image": "/users/images/1315648.jpg"
                    },
                    
                ],
                "topics": [
                    {
                        "name": "Doručení slivovice prezidentovi",
                        "responsiblePerson": {
                            "id": 3,
                            "name": "Templeton Peck",
                            "image": "/users/images/1315648.jpg"
                        }
                        "dueDate": "2013-01-31 11:14:05",
                        "status" : {
                            "id": 1,
                            "name": "Ready",
                            "colour": "fff",
                        }
                        "tags": [
                            {
                                "id" : 1,
                                "name": "asap",
                            },
                            {
                                "id" : 2,
                                "name": "alkohol",
                            },
                        ]
                    }
                ]
            }
      
### Úprava skupiny [PUT]
+ Response 200 (application/json)

        {}

      
## Stream [/groups/<id>/posts]
Parametry `pinned=<0-1>`, `page` číslo strany, `limit` počet na stranu

Příspěvky hlavního streamu. Pinned=1 vrací <b>všechny připnuté příspěvky</b>

Atributy postu:

- `type` - 1 pokud se jedná o klasický příspěvek a obsahuje parametr `message`, 2 pokud jde o událost(i) a obsahuje `events` (př. přidání uživatele do skupiny)


### Načtení příspěvků [GET]
+ Response 200 (application/json)

    + Body

            { 
                "total": 500,
                "page": 0,
                "limit": 20,
                "posts": [
                    {
                        "type" : 1,
                        "user": {
                            "id": 3,
                            "name": "Templeton Peck",
                            "image": "/users/images/1315648.jpg"
                        },
                        "message": {
                            "createdDate": "2013-01-31 11:14:05",
                            "modifiedDate": "2013-01-31 11:14:05",
                            "content": "Přeji všem úspěšnou akci"
                        }
                    },
                    {
                        "type" : 2,
                        "user": {
                            "id": 3,
                            "name": "Templeton Peck",
                            "image": "/users/images/1315648.jpg"
                        },
                        "events": [
                            {
                                "id": 1,
                                "type": 1,
                                "createdDate": "2013-01-31 11:14:05",
                            },
                            {
                                "id": 2,
                                "type": 2,
                                "createdDate": "2013-01-31 11:14:05",
                            }
                        ]
                    }
                ]
            }
      
### Vytvoření příspěvku [POST]
Pole `files` obsahuje ID souborů z volání `/groups/<id>/temporary-files`
+ Request (application/json)

        {
            "content": "Ahoj Františku, jak se máš?",
            "files": [ 1, 2 , 4]
        }
    
+ Response 201 (application/json)

        {   
            "id" : 1
        }


## Post [/groups/<id>/posts/<id>] 
### Detail příspěvku [GET]

+ Response 200 (application/json)

        {
            "type" : 1,
            "user": {
                "id": 3,
                "name": "Templeton Peck",
                "image": "/users/images/1315648.jpg"
            },
            "message": {
                "createdDate": "2013-01-31 11:14:05",
                "modifiedDate": "2013-01-31 11:14:05",
                "content": "Přeji všem úspěšnou akci"
            }
        }


            
## Adresáře [/groups/<id>/directories{/<directoryId>}]
Pokud je `directoryId` prázdné, bere se v úvahu kořen

Atributy položky:

- `type` - 1 soubor, 2 složka, 3 google drive...
    
### Obsah adresáře [GET]
+ Response 200 (application/json)

    + Body

            {
                "id": 1,
                "name": "Tajné dokumenty",
                "content": [
                    {
                        "id": 1,
                        "user": {
                            "id": 3,
                            "name": "Templeton Peck",
                            "image": "/users/images/1315648.jpg"
                        },
                        "type": 1,
                        "kind": "excel file",
                        "name": "Tabulka",
                        "modifiedDate": "2013-01-31 11:14:05",
                    }
                ]
                "parent": {
                    "id": 3,
                    "name": "Všechny tajnosti",
                    "parent": {
                        {
                            "id": 5,
                            "name": "Hlavní složka",
                            "parent": null
                        }
                    }
                }
            }

### Nový adresář [POST]
Volitelný parametr `directoryId` zde slouží jako nadřazená složka

Omezení:

- `name` - maximální délka 100 znaků
    
+ Request (application/json)

        {
            "name": "Soubor",

        }
+ Response 200 (application/json)

        {
        
        }

## Dočasný soubor [/groups/<id>/temporary-files]
### Nový soubor [POST]
Slouží k uploadování souborů přes nový příspěvek. Soubor je nejprve uložen na dočasné uložiště, poté je potřeba přiřadit jeho ID k novému příspěvku ve volání `POST /posts`

Pokud soubory nejsou spárovány s příspěvkem, jsou automaticky smazány za XX hodin.

Omezení:

- `filename` - maximální délka 200 znaků (včetně koncovky), zbytek se ořízne

+ Request (application/json)

        Soubor
        
+ Response 201 (application/json)

        {
            "id": 2,
            ... todo parametry potřebné na frontend
        }


## Soubor [/groups/<id>/files{/<directoryId>}]
### Nový soubor přes Files [POST]
Slouží k uploadování souborů přes sekci FILES (vytváří notifikace). Pro nahrávní souborů přes Post použijte `asd`

Omezení:

- `filename` - maximální délka 200 znaků (včetně koncovky), zbytek se ořízne


+ Request (application/json)

        Soubor
        
+ Response 201 (application/json)

        {
            ... todo parametry potřebné na frontend
        }





# Group Téma

## Topic collection [/groups/<id>/topics]

### Témata skupiny [GET]

+ Response 200 (application/json)


        [
            {
                "id": 1, 
                "name": "Tajné mise",
                "priority": 3,
                "creator": {
                    "id": 1,
                    "name": "B. A. Baracus",
                },
                "group":{
                    "id": 1,
                    "name": "A-Team"
                },
                "responsiblePerson": {
                    "id": 3,
                    "name": "Templeton Peck",
                    "image": "/users/images/1315648.jpg"
                }
                "dueDate": "2013-01-31 11:14:05",
                "status" : {
                    "id": 1,
                    "name": "Ready",
                    "colour": "fff",
                }
                "tags": [
                    {
                        "id" : 1,
                        "name": "asap",
                    },
                    {
                        "id" : 2,
                        "name": "alkohol",
                    },
                ]
                "notifications": []
            }
        ]


### Vytvoření tématu [POST]
+ Request (application/json)

        {
            "name": "Tajné skupiny"
        }
        
+ Response 201 (application/json)

        {}

## Topic [/groups/<id>/topics/<id>]
### Téma skupiny [GET]
+ Response 200 (application/json)

        {
            "id": 1, 
            "name": "Tajné mise",
            "priority": 3,
            "creator": {
                "id": 1,
                "name": "B. A. Baracus",
            },
            "group":{
                "id": 1,
                "name": "A-Team"
            },
            "responsiblePerson": {
                "id": 3,
                "name": "Templeton Peck",
                "image": "/users/images/1315648.jpg"
            }
            "dueDate": "2013-01-31 11:14:05",
            "status" : {
                "id": 1,
                "name": "Ready",
                "colour": "fff",
            }
            "tags": [
                {
                    "id" : 1,
                    "name": "asap",
                },
                {
                    "id" : 2,
                    "name": "alkohol",
                },
            ]
            "notifications": []
        }

## Stream [/groups/<id>/topics/<id>/posts{?pinned=<0-1>}]

Atributy postu:

- `type` - 1 pokud se jedná o klasický příspěvek a obsahuje parametr `message`, 2 pokud jde o událost(i) a obsahuje `events` (př. přidání uživatele do skupiny)


### Příspěvky [GET]
+ Response 200 (application/json)

    + Body

            { 
                "total": 500,
                "page": 0,
                "limit": 20,
                "posts": [
                    {
                        "type" : 1,
                        "user": {
                            "id": 3,
                            "name": "Templeton Peck",
                            "image": "/users/images/1315648.jpg"
                        },
                        "message": {
                            "createdDate": "2013-01-31 11:14:05",
                            "modifiedDate": "2013-01-31 11:14:05",
                            "content": "Přeji všem úspěšnou akci"
                        }
                    },
                    {
                        "type" : 2,
                        "user": {
                            "id": 3,
                            "name": "Templeton Peck",
                            "image": "/users/images/1315648.jpg"
                        },
                        "events": [
                            {
                                "id": 1,
                                "type": 1,
                                "createdDate": "2013-01-31 11:14:05",
                            },
                            {
                                "id": 2,
                                "type": 2,
                                "createdDate": "2013-01-31 11:14:05",
                            }
                        ]
                    }
                ]
            }






