FORMAT: 1A
HOST: http://www.google.com


# grups
Notes API is a *short texts saving* service similar to its physical paper presence on your table.

# Group Skupina
Základní stavební jednotkou je skupina


<table>
<tr>
    <th>Atribut</th>
    <th>Popis</th>
    <th>Typ</th>
    <th>Přístup</th>
    <th>Detail</th>
</tr>

<tr>
    <td>id</td>
    <td>identifikátor</td>
    <td>integer</td>
    <td>r</td>
    <td>Autoincrement</td>
</tr>
<tr>
    <td>*name</td>
    <td>název skupiny</td>
    <td>string,100</td>
    <td>r/w</td>
    <td></td>
</tr>
<tr>
    <td>createdDate</td>
    <td>datum vytvoření</td>
    <td>datetime</td>
    <td>r</td>
    <td></td>
</tr>
<tr>
    <td>modifiedDate</td>
    <td>datum změny</td>
    <td>datetime</td>
    <td>r</td>
    <td></td>
</tr>
<tr>
    <td>hash</td>
    <td>datum změny</td>
    <td>datetime</td>
    <td>r</td>
    <td></td>
</tr>
<tr>
    <td>image</td>
    <td>obrázek v hlavičce</td>
    <td>string</td>
    <td>r</td>
    <td></td>
</tr>
<tr>
    <td>userId</td>
    <td>vlastník</td>
    <td>integer</td>
    <td>r</td>
    <td></td>
</tr>


</table>











## Groups Collection [/groups]
### Seznam skupin [GET]
+ Response 200 (application/json)

        [
            {
                "id": 1, 
                "name": "A-Team",
                "category": {
                    "name": "Heroes",  
                },
                "creator": {
                    "id": 1,
                    "name": "B. A. Baracus",
                },
                "members": [
                    {
                        "id": 2,
                        "name": "John Smith",
                        "image": "/users/images/1315648.jpg"
                        "admin": true
                    },
                    {
                        "id": 3,
                        "name": "Templeton Peck",
                        "image": "/users/images/1315648.jpg",
                        "admin": false
                    },
                    
                ],
                "notifications": []
            }
        ]



## Group [/groups/{id}]
Popis skupiny

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Note to perform action with. Has example value.

### Skupina [GET]
+ Response 200 (application/json)

    + Body

            { 
                "id": 1,
                "name": "A-Team",
                "members": [
                    {
                        "id": 2,
                        "name": "John Smith",
                        "image": "/users/images/1315648.jpg"
                    },
                    {
                        "id": 3,
                        "name": "Templeton Peck",
                        "image": "/users/images/1315648.jpg"
                    },
                    
                ],
                "topics": [
                    {
                        "name": "Doručení slivovice prezidentovi",
                        "responsiblePerson": {
                            "id": 3,
                            "name": "Templeton Peck",
                            "image": "/users/images/1315648.jpg"
                        }
                        "dueDate": {
                            "date": "2013-01-31 11:14:05",
                            "timezoneType": 3,
                            "timezone": "America\/Los_Angeles"
                        }
                        "status" : {
                            "id": 1,
                            "name": "Ready",
                            "colour": "fff",
                        }
                        "tags": [
                            {
                                "id" : 1,
                                "name": "asap",
                            },
                            {
                                "id" : 2,
                                "name": "alkohol",
                            },
                        ]
                    }
                ]
            }
      
## Stream [/groups/{id}/posts]
Příspěvky hlavního streamu skupiny (bez připnutých příspěvků), pro kompletní výpis je potřeba zavolat také `/groups/{id}/posts` 

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Note to perform action with. Has example value.

### Skupina [GET]
+ Response 200 (application/json)

    + Body

            { 
                "posts": [
                    {
                        "type" : 1,
                        "user": {
                            "id": 3,
                            "name": "Templeton Peck",
                            "image": "/users/images/1315648.jpg"
                        },
                        "message": {
                            "createdDate": {
                                "date": "2013-01-31 11:14:05",
                                "timezoneType": 3,
                                "timezone": "America\/Los_Angeles"
                            },
                            "modifiedDate": {
                                "date": "2013-01-31 11:14:05",
                                "timezoneType": 3,
                                "timezone": "America\/Los_Angeles"
                            },
                            "content": "Přeji všem úspěšnou akci"
                        }
                    },
                    {
                        "type" : 2,
                        "user": {
                            "id": 3,
                            "name": "Templeton Peck",
                            "image": "/users/images/1315648.jpg"
                        },
                        "events": [
                            {
                                "id": 1,
                                
                            }
                        ]
                    }
                ]
            }
      
            
## Group [/groups/{id}/posts?pinned=1]
Připnuté příspěvky hlavního streamu skupiny

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Note to perform action with. Has example value.

### Skupina [GET]
+ Response 200 (application/json)

    + Body

            { 
                "posts": [
                    "user": {
                        "id": 3,
                        "name": "Templeton Peck",
                        "image": "/users/images/1315648.jpg"
                    },
                    "message": {
                        "createdDate": {
                            "date": "2013-01-31 11:14:05",
                            "timezoneType": 3,
                            "timezone": "America\/Los_Angeles"
                        },
                        "modifiedDate": {
                            "date": "2013-01-31 11:14:05",
                            "timezoneType": 3,
                            "timezone": "America\/Los_Angeles"
                        },
                        "content": "UPOZORNĚNÍ: Akce se bude konat příští měsíc"
                    }
                ]
            }







